### ISSUE TITLE
Install xvfb inside the container

### ISSUE THREAD

**Issue by leosuncin** [beevelop/docker-android-nodejs#172]
Hello,

I use [cypress](https://docs.cypress.io/guides/overview/why-cypress.html) for run the integration tests, but it have its own [dependencies](https://on.cypress.io/required-dependencies) in order to run electron in headless mode.
```bash
apt-get install -qq -y --no-install-recommends libxtst6 libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
```
Could you install this dependecies?

Thanks again

**Comment by beevelop** [comment]
That's a pretty specific use case and most people won't need this dependencies in this image. What about building a respective child image? Like so:
```dockerfile
FROM beevelop/android-nodejs:latest

RUN apt-get install -qq -y --no-install-recommends libxtst6 libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
```

This allows you to tailor this image to your specific needs. You can even publish your child image on Docker Hub in order to simplify your CI / CD pipeline.
